[package]
name = "o-mechanics"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16"
bevy-fps-counter = "0.7.0"
bevy_console = "0.14"
bevy_infinite_grid = "0.15"
bevy_panorbit_camera = "0.26"
clap = { version = "4.5.38", features = ["derive"] }
